### ISSUE TITLE
한국어판 대응 / Korean version support

### ISSUE THREAD

**Issue by Kimjio** [Kimjio/umamusume-localify#10]
### 들어가기 전
- 보안 솔루션
  - 일본어판과 비슷한 수준이라면 OK
  - 그렇지 않다면, 다른 방법 필요 (또는 불가능)

### TODO
- [x] 일본어판, 한국어판 구분
- [ ] ~Unity 버전에 따라 일부 다르게 적용~
- [ ] Android 한국어판 기능 이식

**Comment by Kimjio** [comment]
23.06.15
유니티 2020.3.47f1로 업데이트

**Comment by Kimjio** [comment]
![image](https://github.com/Kimjio/umamusume-localify/assets/10695980/936ca329-88ba-47d3-a0fc-1e80b9bf49b1)

**Comment by Kimjio** [comment]
version.dll 로드는 문제 없음, il2cpp_symbols 초기화 중 오류 발생

**Comment by Kimjio** [comment]
il2cpp를 사용하지 않음, Mono 그대로 사용

**Comment by Kimjio** [comment]
https://github.com/Kimjio/umamusume-localify-mono

**Comment by Kimjio** [comment]
il2cpp로 빌드 타입 변경

**Comment by Kimjio** [comment]
AppSign, Uncheater (XIGNCODE3) 사용
Beebyte's Obfuscator 적용됌

**Comment by Kimjio** [comment]
> Beebyte's Obfuscator 적용됌

2025-06-14 업데이트로 제거

**Comment by yeonggille** [comment]
안녕하세요, 선생님. 언제나 유지보수에 고생이 많으십니다.
한국어판 umamusume.exe 쪽으로 파일을 넣고 실행하면
오류코드 0xc0000142가 뜨면서 실행이 안되는데 아직 완성이 안 된건가요?

**Comment by Kimjio** [comment]
> 안녕하세요, 선생님. 언제나 유지보수에 고생이 많으십니다. 한국어판 umamusume.exe 쪽으로 파일을 넣고 실행하면 오류코드 0xc0000142가 뜨면서 실행이 안되는데 아직 완성이 안 된건가요?

`umamusume.exe.local` 폴더가 존재하나요?
한국어판은 DLL Redirection 기능이 필요하지 않아 삭제하면 됩니다.
(imm32.dll은 일본어 판에서만 필요/사용 가능합니다. 이 외 프로그램에서는 오류 발생하는데 이유는 모릅니다.)


`localify.dll`은 `version.dll`로 변경하면 적용됩니다.

**Comment by Kimjio** [comment]
> 말씀해 주신대로 umamusume.exe.local 폴더를 삭제하고 localify.dll을 version.dll로 변경하였더니 안드로이드 루팅하고 shamiko를 안 깔았을때처럼 "이 기기에서는 플레이할 수 없습니다" 라고 안내문이 뜹니다

@yeonggille 의도된 동작입니다.
그 화면에서 ⬆️⬆️⬇️⬇️⬅️➡️⬅️➡️🅱️🅰️ 입력하시면 됩니다.

**Comment by yeonggille** [comment]
감사합니다. 언제나 유지보수에 고생 많으십니다!
아직 더위가 끝까지 가시지 않았으니 건강 유의하시길 바랍니다
